name: Testes com pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
          pip install mysqlclient

      - name: Configurar MySQL
        run: |
          sudo apt-get install -y mysql-server
          sudo service mysql start
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'auth_socket';"
          sudo mysql -e "FLUSH PRIVILEGES;"
          sudo mysql -e "SOURCE lembremed/lembremed/create_database.sql"

      - name: Definir variável de ambiente do Django
        run: echo "DJANGO_SETTINGS_MODULE=lembremed.settings" >> $GITHUB_ENV

      - name: Migrar banco de dados
        run: python manage.py migrate

      - name: Rodar testes
        run: pytest
