name: Testes com pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
          pip install mysqlclient

      - name: Instalar e configurar MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo service mysql start
          
          # Iniciar MySQL sem autenticação
          sudo mysqld_safe --skip-grant-tables --skip-networking &
          
          # Esperar o MySQL iniciar
          sleep 5
          
          # Executar comandos para criar banco e definir senha
          sudo mysql -e "FLUSH PRIVILEGES;"
          sudo mysql -e "CREATE DATABASE lembremed;"
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"
          sudo mysql -e "FLUSH PRIVILEGES;"
          
          # Encerrar o MySQL
          sudo killall mysqld

      - name: Definir variável de ambiente do Django
        run: echo "DJANGO_SETTINGS_MODULE=lembremed.settings" >> $GITHUB_ENV

      - name: Migrar banco de dados
        run: python manage.py migrate

      - name: Rodar testes
        run: pytest
