name: Testes com pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
          pip install mysqlclient

      - name: Instalar e configurar MySQL
        run: |
          # Instalar MySQL Server se não estiver instalado
          if ! command -v mysql &> /dev/null; then
            sudo apt-get install -y mysql-server
          fi
          sudo service mysql start
          sleep 5

          # Redefina a senha do root
          echo "Redefinindo senha para o usuário root..."
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'nova_senha_secreta';"

          # Criar o banco de dados
          echo "Criando banco de dados lembremed..."
          if ! sudo mysql -uroot -pnova_senha_secreta -e "CREATE DATABASE lembremed;"; then
            echo "Erro ao criar banco de dados."
            exit 1
          fi

          # Criar um novo usuário e conceder privilégios
          echo "Criando usuário testuser e concedendo privilégios..."
          if ! sudo mysql -uroot -pnova_senha_secreta -e "CREATE USER 'testuser'@'localhost' IDENTIFIED BY 'password';"; then
            echo "Erro ao criar usuário."
            exit 1
          fi

          if ! sudo mysql -uroot -pnova_senha_secreta -e "GRANT ALL PRIVILEGES ON lembremed.* TO 'testuser'@'localhost';"; then
            echo "Erro ao conceder privilégios."
            exit 1
          fi

          # Finalizar
          sudo mysql -uroot -pnova_senha_secreta -e "FLUSH PRIVILEGES;"
      
      - name: Definir variável de ambiente do Django
        run: echo "DJANGO_SETTINGS_MODULE=lembremed.settings" >> $GITHUB_ENV

      - name: Migrar banco de dados
        run: python manage.py migrate

      - name: Rodar testes
        run: pytest
