name: Testes com pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
          pip install mysqlclient

      - name: Instalar e configurar MySQL
        run: |
          sudo apt-get install -y mysql-server
          sudo service mysql start
          sleep 5

          # Criar um arquivo de configuração temporário para permitir o acesso
          echo "[mysqld]" | sudo tee /etc/mysql/conf.d/mysqld.cnf
          echo "skip-grant-tables" | sudo tee -a /etc/mysql/conf.d/mysqld.cnf
          sudo service mysql restart
          sleep 5

          # Conectar ao MySQL sem senha e criar o banco de dados
          sudo mysql --skip-password -e "CREATE DATABASE lembremed;"

          # Remover o arquivo de configuração temporário
          sudo rm /etc/mysql/conf.d/mysqld.cnf
          sudo service mysql restart
          sleep 5

          # Criar o usuário e conceder privilégios
          sudo mysql --skip-password -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'root';"
          sudo mysql --skip-password -e "GRANT ALL PRIVILEGES ON lembremed.* TO 'root'@'localhost';"
          sudo mysql --skip-password -e "FLUSH PRIVILEGES;"

      - name: Definir variável de ambiente do Django
        run: echo "DJANGO_SETTINGS_MODULE=lembremed.settings" >> $GITHUB_ENV

      - name: Migrar banco de dados
        run: python manage.py migrate

      - name: Rodar testes
        run: pytest
