name: Testes com pytest
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
          pip install mysqlclient

      - name: Instalar e configurar MySQL
        run: |
          # Instalar MySQL Server se não estiver instalado
          if ! command -v mysql &> /dev/null; then
            sudo apt-get install -y mysql-server
          fi
          sudo service mysql stop
          sudo mysqld_safe --skip-grant-tables &
          sleep 5

          # Redefinir a senha do root
          echo "Redefinindo senha para o usuário root..."
          sudo mysql -e "UPDATE mysql.user SET authentication_string=null WHERE User='root';"
          sudo mysql -e "UPDATE mysql.user SET plugin='mysql_native_password' WHERE User='root';"
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'nova_senha_secreta';"
          sudo mysql -e "FLUSH PRIVILEGES;"
          sudo service mysql restart
          sleep 5

          # Criar o banco de dados
          echo "Criando banco de dados lembremed..."
          sudo mysql -uroot -pnova_senha_secreta -e "CREATE DATABASE lembremed;"

          # Criar um novo usuário e conceder privilégios
          echo "Criando usuário testuser e concedendo privilégios..."
          sudo mysql -uroot -pnova_senha_secreta -e "CREATE USER 'testuser'@'localhost' IDENTIFIED BY 'password';"
          sudo mysql -uroot -pnova_senha_secreta -e "GRANT ALL PRIVILEGES ON lembremed.* TO 'testuser'@'localhost';"

          # Finalizar
          sudo mysql -uroot -pnova_senha_secreta -e "FLUSH PRIVILEGES;"
      
      - name: Definir variável de ambiente do Django
        run: echo "DJANGO_SETTINGS_MODULE=lembremed.settings" >> $GITHUB_ENV

      - name: Migrar banco de dados
        run: python manage.py migrate

      - name: Rodar testes
        run: pytest
